### ISSUE TITLE
Not able to download credits and people details

### ISSUE THREAD

**Issue by harshit-yadav** [D-Andreev/tmdb-script#4]
Hi,

I am using this script to download TMDB Data but not able to download credits and peoples details.
When I started with steps like -s "credits/people", it always starts with similar and stops after that.
can you please confirm I am missing something or there is an issue in this?

Thanks,
Harshit

**Comment by D-Andreev** [comment]
Hi Harshit,

Yes I see there is a bug here - https://github.com/D-Andreev/tmdb-script/blob/master/src/TmdbScript.js#L593 
This line should be `U.downloadMovieData('credits', U.getMovieCredits, EVENTS.CREDITS_DOWNLOADED);`

When you pass in the step for `credits` it starts to download `similar` instead. I can fix this in the next couple of days, or you can make a PR if you want :)

Cheers,
Dimitar

**Comment by D-Andreev** [comment]
Fixed with: https://github.com/D-Andreev/tmdb-script/pull/5
